[[constraint]]
  name = "github.com/docker/machine"
  version = "0.16.1"

[[constraint]]
  name = "github.com/moby/moby"
  version = "17.03.2-ce"  

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "golang.org/x/sys"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
