[[constraint]]
  name = "github.com/moby/moby"
  version = "17.03.2-ce"  

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
